### ISSUE TITLE
Case insensitivity for Http Headers [5]

### ISSUE THREAD

**Issue by essal0815** [hpi-swa-teaching/RatPack2.0#95]
Till yet the headers can be set, but
"Content-Type" and "content-type" are different fields.

Because of HttpResponse Class in Squeak, we have to handle status, contentType, contentLength, cookies different (separate instance variables)

Idea/wish:
setting normal fields always capitalized beginning and dash separated
setting all headers with headersPut: aDictionary shall also set HttpResponse instance vars

**Comment by He3lixxx** [comment]
I think the inconvenience is completely in `HttpResponse` and not in our code. Thus, I would simply remove the `RPApplication` accessor `headers:` and `headers`. Whenever you want to set headers, manipulate the response directly. Then, it's not our fault anymore. If we do it like this, 5 from me.

**Comment by essal0815** [comment]
But we need the accessor so the header manipulation is Sinatra like ...

sinatra does
headers[key] = value

RatPack does
self headersAt: key put: value

**Comment by He3lixxx** [comment]
Alright, we agreed on the following:
- [ ] RPApplication offers an accessing method (`headersAt:put:`). This checks case insensitively for the three edge cases (content-type, status, cookies). If the key matches, we set use the corresponding accessor of the HttpResponse. Otherwise, we set the field of the HttpResponse.
- [ ] Also, we offer 2 convenience methods, contentType and status, which are a shorthand for `headersAt: 'content-type' put: X` and `headersAt: 'status' put: X`.

**Comment by skydivin4ng3l** [comment]
5

**Comment by Nina510** [comment]
5

**Comment by jakobmache** [comment]
5

**Comment by richardebeling** [comment]
Related to #68.

Why did you close this? The PR is not merged and we don't have product owner approval afaik.
