### ISSUE TITLE
Useful error message if model is not registered / 404 Handling [8]

### ISSUE THREAD

**Issue by essal0815** [hpi-swa-teaching/RatPack2.0#97]
At the moment it is quit hard to see that the only problem is a missing registration of Model
Error:  wrong arguments in handler calling-> check that handler is #notFound ...

Issue:
If /api/... is called and URL is not found -> handler is #notFound But arguments are provided.
We have to prevent perform: #notFound withArguments: args

Maybe in general useful to rethink 404 handling

**Comment by He3lixxx** [comment]
First of all, I think handling #notFound like a normal handler is a rather bad idea, but at this point, I'm not really into rewriting it.

I think the issue is that RPApplication sets the handler in `route` when it calls `setRouteHandler`, but the MiddlewareCallchainAdapter tries to figure out the arguments in `handle:next:`. One of these two should either do both or nothing. 5 from me.

**Comment by essal0815** [comment]
How else could the notFound be handled except than handler ? Is it a lot to rewrite ?

setRouteHandler and setArguments at one place sounds as a good idea.

My Estimation: 8

**Comment by He3lixxx** [comment]
IMO notFound should be a convenience method that sets the status and writes the response body, then returns. The CallchainHandlerAdapterMiddleware should get the appropriate handler and call it or - if it does not exist - execute notFound and return. This would be a cleaner way in my opinion. But I guess we get accessing problems then since some information is not available there (e.g. a middleware does not have a reference to the application, thus it has no access to the routes), so I guess we'll be going with settings the handler and the handler arguments in the application before the middleware callchain is started.

**Comment by skydivin4ng3l** [comment]
13 cause im not sure how this should be implemented e.g. i do not unterstand the comments in total.

**Comment by essal0815** [comment]
We have to do it all in `route:` because the callchain needs the handler.

**Comment by Nina510** [comment]
8

**Comment by jakobmache** [comment]
8

**Comment by essal0815** [comment]
@He3lixxx I red your comment again and I think we can do it this clean way. I think the callChainAdapter can do all this.
The adapter has a reference to the application to execute the handlers on it...
So we can put an empty adapter in the callChain, and look for the data(handler and arguments) in the adapter.

**Comment by richardebeling** [comment]
This is a duplication of / part of #82.
